# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_camadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('bias', models.BooleanField(default=False)),
                ('learningrate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('momentum', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('epochs', models.IntegerField()),
                ('erro_max', models.FloatField()),
                ('peso_start', models.FloatField()),
                ('peso_end', models.FloatField()),
            ],
        ),
    ]
