# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 18:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignetwork',
            name='name',
            field=models.CharField(default='padrao', max_length=30),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='epochs',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='erro_max',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='learningrate',
            field=models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='momentum',
            field=models.FloatField(default=0.99, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='num_camadas',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='peso_end',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='confignetwork',
            name='peso_start',
            field=models.FloatField(default=-1),
        ),
    ]
