# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0002_auto_20170615_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sexo', models.IntegerField()),
                ('tipo_objetivos', models.IntegerField()),
                ('tipo_preferencias', models.IntegerField()),
                ('tipo_doencas', models.IntegerField()),
                ('tipo_dias', models.IntegerField()),
                ('result1', models.IntegerField()),
                ('result2', models.IntegerField()),
                ('result3', models.IntegerField()),
            ],
        ),
    ]
